# This is the default format.
# For more see: https://github.com/mojombo/jekyll/wiki/Permalinks
permalink: /:year/:month/:title.html
markdown: kramdown
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
auto: false
pygments: true

# Themes are encouraged to use these universal variables
# so be sure to set them if your theme uses them.
#
title : goxc
tagline: cross-compile Go programs to several platforms at once
author :
  name : Am Laher
  email : am@laher.net.nz
  github : laher

# The production_url is only used when full-domain names are needed
# such as sitemap.txt
# Most places will/should use BASE_PATH to make the urls
#
# If you have set a CNAME (pages.github.com) set your custom domain here.
# Else if you are pushing to username.github.com, replace with your username.
# Finally if you are pushing to a GitHub project page, include the project name at the end.
#
production_url : http://laher.github.com/goxc
